### ISSUE TITLE
Error during repo sync

### ISSUE THREAD

**Issue by 0E800** [followmsi/manifests#1]
Hello, thank you for your contribution towards the internet. 

I have successfully built RR-Pie for the N7-Flo using your manifest.

I am trying to build the same ROM for N7-Deb but am receiving this error when I try to sync.
*****

`GitError: followmsi/android_device_asus_deb rev-list ('^02a827861d670a3e762b2a1dab9adbab50ebbc01', 'HEAD', '--'): fatal: bad object HEAD` 

Googling the error mentions corrupt data. 

May you suggest a work around I can try?

Ref: https://github.com/followmsi/manifests/tree/flo-deb-rros-lineage-16.0

**Comment by 0E800** [comment]
I am attempting a new repo init from scratch in a new folder, whereas previously I was re-syncing in a previously used repo folder.

**Comment by 0E800** [comment]
EBCAK  
Apologies, please disregard and mark issue as solved.

Fresh repo worked.

**Comment by followmsi** [comment]
Next time you can try "repo sync --force-sync" command .. this way it should work on exisiting repo (folder) too.

Let's close this issue now.
